FROM selenium/standalone-firefox:3.141.5

COPY server/target/scala-2.12/remote-test-proxy-server.jar /opt/remote-test-proxy-server.jar

COPY server/conf/remote-test-proxy.conf /etc/supervisor/conf.d/remote-test-proxy.conf
